# -*- coding: utf-8 -*-
"""5 years demand envelope.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10XTmM0KqtvRyrd_2JxD2yna6T6J_dklq
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
from IPython.display import FileLink
import requests
# Load the CSV file
data = pd.read_csv('5 years demand.csv')
print(data)
# Specify the column and the term to delete
df = pd.DataFrame(data)

# Step 3: Select the columns you want to keep
# Replace 'column_1' and 'column_2' with the actual columns you want
new_df = df[['utc_timestamp', 'GB_GBN_load_actual_entsoe_transparency']]

# Step 4: Display the new dataset
print(new_df)
new_df.to_csv('GBN_dataset.csv', index=False)
files.download('GBN_dataset.csv')

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
from IPython.display import FileLink
import requests
# Load the CSV file
data = pd.read_csv('5_years_GBN_dataset.csv')
print(data)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
dataset1 = pd.read_csv('5_years_GBN_dataset.csv')
df = pd.DataFrame(dataset1)
# Group by 'x' and aggregate y values into lists
grouped = df.groupby('utc_timestamp')['GB_GBN_load_actual_entsoe_transparency'].apply(list).reset_index()
power = grouped['GB_GBN_load_actual_entsoe_transparency']
dates = grouped['utc_timestamp']
print("\nGrouped DataFrame with separated y values:")
print(grouped)
max_power_values = [max(power_values) for power_values in power]

# Creating a dictionary to display the results
max_power_dict = dict(zip(dates, max_power_values))

# Print the results
for date, max_power in max_power_dict.items():
    print(f"Date: {date}, Maximum Power: {max_power}")
# Display the grouped DataFrame
colors = plt.cm.viridis(np.linspace(0, 1, len(power)))

# Define the logistic function
def logistic(x, L, k, x0):
    return L / (1 + np.exp(-k * (x - x0)))
d=50638
# Fit the logistic function to the data
initial_guess = [d, 1, np.median(dates)]  # Initial guess for L, k, x0
params, covariance = curve_fit(logistic, dates, max_power_values, p0=initial_guess)

# Extract parameters
L, k, x0 = params

# Generate values for the fitted logistic function
upper_bound = logistic(dates, L, k, x0)  + 7000
lower_bound = - (logistic(dates, L, k, x0)) + 48000
# Plotting
plt.figure(figsize=(10, 5))

for i, demand_values in enumerate(power):
    # Create indices for the demand values to use on the x-axis for each date
    x_indices = [dates[i]] * len(demand_values)  # Repeat the date for the length of power values
    plt.scatter(x_indices, demand_values, color=colors[i])  # Scatter points
plt.plot(dates, upper_bound, label='Logistic Fit', color='red')
plt.plot(dates, lower_bound, label='Logistic Fit', color='red')
# Adding aesthetics
plt.title('demand Values Over intra time steps')
plt.xlabel('Time')
plt.ylabel('Demand')
plt.xticks(dates)  # Set x-ticks to show the dates clearly
plt.legend()
plt.grid()
plt.show()