# -*- coding: utf-8 -*-
"""Real Comparison Rehab vs New .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Ol0A3H7hzQeGATqJfASUJlOWXovo_1f
"""

!pip install pulp

!apt-get install -y glpk-utils  # Install GLPK
!pip install pulp  # Install PuLP

from pulp import LpProblem, LpMinimize, LpVariable, lpSum, LpStatus, GLPK
from pulp import CPLEX_CMD
# Updated Generator Features
generators = [
    {"name": "gen04", "RampUp": 60, "RampDown": 60, "Startup": 150, "Pmax": 300, "Pmin": 150, "StartupCost": 440},
    {"name": "gen05", "RampUp": 60, "RampDown": 60, "Startup": 100, "Pmax": 300, "Pmin": 100, "StartupCost": 110},
    {"name": "gen07", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen10", "RampUp": 60, "RampDown": 60, "Startup": 100, "Pmax": 300, "Pmin": 100, "StartupCost": 100},
    {"name": "gen11", "RampUp": 70, "RampDown": 70, "Startup": 100, "Pmax": 350, "Pmin": 100, "StartupCost": 100},
    {"name": "gen14", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen16", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen19", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 59},
    {"name": "gen20", "RampUp": 50, "RampDown": 50, "Startup": 50, "Pmax": 250, "Pmin": 50, "StartupCost": 100},
    {"name": "gen21", "RampUp": 50, "RampDown": 50, "Startup": 50, "Pmax": 250, "Pmin": 50, "StartupCost": 100},
    {"name": "gen22", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen23", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen24", "RampUp": 40, "RampDown": 40, "Startup": 50, "Pmax": 200, "Pmin": 50, "StartupCost": 100},
    {"name": "gen25", "RampUp": 40, "RampDown": 40, "Startup": 50, "Pmax": 200, "Pmin": 50, "StartupCost": 100},
    {"name": "gen26", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen27", "RampUp": 84, "RampDown": 84, "Startup": 100, "Pmax": 420, "Pmin": 100, "StartupCost": 600},
    {"name": "gen28", "RampUp": 84, "RampDown": 84, "Startup": 100, "Pmax": 420, "Pmin": 100, "StartupCost": 600},
    {"name": "gen29", "RampUp": 60, "RampDown": 60, "Startup": 80, "Pmax": 300, "Pmin": 80, "StartupCost": 100},
    {"name": "gen30", "RampUp": 66.7, "RampDown": 66.7, "Startup": 30, "Pmax": 80, "Pmin": 30, "StartupCost": 45},
    {"name": "gen34", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen35", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen36", "RampUp": 60, "RampDown": 60, "Startup": 150, "Pmax": 300, "Pmin": 150, "StartupCost": 440},
    {"name": "gen37", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen39", "RampUp": 60, "RampDown": 60, "Startup": 100, "Pmax": 300, "Pmin": 100, "StartupCost": 440},
    {"name": "gen40", "RampUp": 40, "RampDown": 40, "Startup": 50, "Pmax": 200, "Pmin": 50, "StartupCost": 400},
    {"name": "gen43", "RampUp": 60, "RampDown": 60, "Startup": 100, "Pmax": 300, "Pmin": 100, "StartupCost": 100},
    {"name": "gen44", "RampUp": 60, "RampDown": 60, "Startup": 100, "Pmax": 300, "Pmin": 100, "StartupCost": 100},
    {"name": "gen45", "RampUp": 60, "RampDown": 60, "Startup": 100, "Pmax": 300, "Pmin": 100, "StartupCost": 110},
    {"name": "gen47", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen48", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen51", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen52", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen53", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen01", "RampUp": 25, "RampDown": 25, "Startup": 5, "Pmax": 30, "Pmin": 5, "StartupCost": 40},
    {"name": "gen02", "RampUp": 25, "RampDown": 25, "Startup": 5, "Pmax": 30, "Pmin": 5, "StartupCost": 40},
    {"name": "gen03", "RampUp": 25, "RampDown": 25, "Startup": 5, "Pmax": 30, "Pmin": 5, "StartupCost": 40},
    {"name": "gen06", "RampUp": 25, "RampDown": 25, "Startup": 10, "Pmax": 30, "Pmin": 10, "StartupCost": 40},
    {"name": "gen08", "RampUp": 25, "RampDown": 25, "Startup": 5, "Pmax": 30, "Pmin": 5, "StartupCost": 40},
    {"name": "gen09", "RampUp": 25, "RampDown": 25, "Startup": 5, "Pmax": 30, "Pmin": 5, "StartupCost": 40},
    {"name": "gen12", "RampUp": 25, "RampDown": 25, "Startup": 8, "Pmax": 30, "Pmin": 8, "StartupCost": 40},
    {"name": "gen13", "RampUp": 25, "RampDown": 25, "Startup": 8, "Pmax": 30, "Pmin": 8, "StartupCost": 40},
    {"name": "gen15", "RampUp": 25, "RampDown": 25, "Startup": 8, "Pmax": 30, "Pmin": 8, "StartupCost": 40},
    {"name": "gen17", "RampUp": 25, "RampDown": 25, "Startup": 8, "Pmax": 30, "Pmin": 8, "StartupCost": 40},
    {"name": "gen18", "RampUp": 25, "RampDown": 25, "Startup": 8, "Pmax": 30, "Pmin": 8, "StartupCost": 40},
    {"name": "gen31", "RampUp": 25, "RampDown": 25, "Startup": 10, "Pmax": 30, "Pmin": 10, "StartupCost": 40},
    {"name": "gen32", "RampUp": 25, "RampDown": 25, "Startup": 5, "Pmax": 30, "Pmin": 5, "StartupCost": 40},
    {"name": "gen33", "RampUp": 16/7, "RampDown": 16/7, "Startup": 5, "Pmax": 20, "Pmin": 5, "StartupCost": 30},
    {"name": "gen38", "RampUp": 25, "RampDown": 25, "Startup": 10, "Pmax": 30, "Pmin": 10, "StartupCost": 40},
    {"name": "gen41", "RampUp": 16/7, "RampDown": 16/7, "Startup": 8, "Pmax": 20, "Pmin": 8, "StartupCost": 30},
    {"name": "gen42", "RampUp": 41/7, "RampDown": 41/7, "Startup": 20, "Pmax": 50, "Pmin": 20, "StartupCost": 45},
    {"name": "gen46", "RampUp": 16/7, "RampDown": 16/7, "Startup": 8, "Pmax": 20, "Pmin": 8, "StartupCost": 30},
    {"name": "gen49", "RampUp": 16/7, "RampDown": 16/7, "Startup": 8, "Pmax": 20, "Pmin": 8, "StartupCost": 30},
    {"name": "gen50", "RampUp": 16/7, "RampDown": 16/7, "Startup": 8, "Pmax": 20, "Pmin": 8, "StartupCost": 30},
    {"name": "gen59", "RampUp": 180, "RampDown": 180, "Startup": 180, "Pmax": 30, "Pmin": 5, "StartupCost": 249/9},
    {"name": "gen60", "RampUp": 120, "RampDown": 120, "Startup": 120, "Pmax": 20, "Pmin": 5, "StartupCost": 248/4},
    {"name": "gen61", "RampUp": 180, "RampDown": 180, "Startup": 180, "Pmax": 30, "Pmin": 5, "StartupCost": 269/1},
    {"name": "gen62", "RampUp": 120, "RampDown": 120, "Startup": 120, "Pmax": 20, "Pmin": 5, "StartupCost": 261/3},
    {"name": "gen63", "RampUp": 180, "RampDown": 180, "Startup": 180, "Pmax": 30, "Pmin": 5, "StartupCost": 297/3},
    {"name": "gen64", "RampUp": 120, "RampDown": 120, "Startup": 120, "Pmax": 20, "Pmin": 5, "StartupCost": 279},

]



storages = [
    {"name": "PSH1", "RampUp": 2, "RampDown": 2, "Startup": 100, "StartupCost": 10, "Pmin": 50, "Pmax": 250},
    {"name": "PSH2", "RampUp": 2, "RampDown": 2, "Startup": 100, "StartupCost": 10, "Pmin": 50, "Pmax": 250},
    {"name": "PSH3", "RampUp": 2, "RampDown": 2, "Startup": 100, "StartupCost": 10, "Pmin": 50, "Pmax": 250},
    {"name": "CAES1", "RampUp": 1, "RampDown": 1, "Startup": 50, "StartupCost": 3, "Pmin": 5, "Pmax": 50},
    {"name": "CAES2", "RampUp": 1, "RampDown": 1, "Startup": 50, "StartupCost": 3, "Pmin": 5, "Pmax": 50},
    {"name": "CAES3", "RampUp": 1, "RampDown": 1, "Startup": 50, "StartupCost": 3, "Pmin": 5, "Pmax": 50},
    {"name": "LiION1", "RampUp": 12, "RampDown": 12, "Startup": 20, "StartupCost": 4, "Pmin": 1, "Pmax": 5},
    {"name": "LiION2", "RampUp": 12, "RampDown": 12, "Startup": 20, "StartupCost": 4, "Pmin": 1, "Pmax": 5},
    {"name": "LiION3", "RampUp": 12, "RampDown": 12, "Startup": 20, "StartupCost": 4, "Pmin": 1, "Pmax": 5},
    {"name": "PSH4", "RampUp": 2, "RampDown": 2, "Startup": 100, "StartupCost": 10, "Pmin": 50, "Pmax": 250},
    {"name": "PSH5", "RampUp": 2, "RampDown": 2, "Startup": 100, "StartupCost": 10, "Pmin": 50, "Pmax": 250},
    {"name": "PSH6", "RampUp": 2, "RampDown": 2, "Startup": 100, "StartupCost": 10, "Pmin": 50, "Pmax": 250},
    {"name": "PSH7", "RampUp": 2, "RampDown": 2, "Startup": 100, "StartupCost": 10, "Pmin": 50, "Pmax": 250},
    {"name": "PSH8", "RampUp": 2, "RampDown": 2, "Startup": 100, "StartupCost": 10, "Pmin": 50, "Pmax": 250},
    {"name": "PSH9", "RampUp": 2, "RampDown": 2, "Startup": 82, "StartupCost": 10, "Pmin": 50, "Pmax": 250},


]
# Demand Upper Bound
demand_data = [
    3291.96, 2358.38, 1726.88, 3255.33,
    4119.83, 4427.13, 3555.79, 3028.29,
    4099.33, 5044.42, 4487.04, 3549.00
]
# Wind generation as a percentage of demand (we assume 10% to 40% of demand)
wind_generation = []

# Calculate wind generation for each interval
for demand in demand_data:
    wind_percentage = random.uniform(0.10, 0.40)  # Random wind percentage between 10% and 40%
    wind_generation.append(demand * wind_percentage)

#Calculate the Net_load
net_load = [demand[i] - wind_generation for i in range(len(demand))]
print(net_load)
# Create Optimization Problem
problem = LpProblem("GeneratorOptimization", LpMinimize)

# Decision Variables
power = {

    **{(g["name"], t): LpVariable(f"power_{g['name']}_{t}", 0, g["Pmax"])
       for g in generators for t in range(len(demand))},
    **{(s["name"], t): LpVariable(f"power_{s['name']}_{t}", 0, s["Pmax"])
       for s in storages for t in range(len(demand))}
}


status = {
    **{(g["name"], t): LpVariable(f"status_{g['name']}_{t}", 0, 1, cat="Binary")
    for g in generators for t in range(len(demand))},
     **{(s["name"], t): LpVariable(f"status_{s['name']}_{t}", 0, 1, cat="Binary")
    for s in storages for t in range(len(demand))}
}

#the estimation of Investment cost of gen26,27,28
Investment_cost = 750000

# Objective Function: Minimize Cost
problem += lpSum(
   (power[g["name"], t] * 135) - (power.get(("gen27", t), 0) * 65
+ power.get(("gen28", t), 0) * 65) + status[g["name"], 0] * g["StartupCost"] +  Investment_cost


    # The next line ensures t+1 does not cause an Index Error by excluding the last element of the range
    for g in generators for t in range(len(demand))
) + lpSum(
    power[s["name"], t] * 62 + status[s["name"], 0] * s["StartupCost"]
    for s in storages for t in range(len(demand))
)

# Constraints
for t in range(len(demand)):
    # Meet Demand
    problem += lpSum(power[g["name"], t] for g in generators) + lpSum(power[s["name"], t] for s in storages) >= net_load[t], f"net_load_{t}"

    # Separate loops for generator and storage constraints:
    for g in generators:
        name_1 = g["name"]
        # Enforce generator minimum and maximum if on
        problem += power[name_1, t] <= status[name_1, t] * g["Pmax"], f"MaxPower_{name_1}_{t}"
        problem += power[name_1, t] >= status[name_1, t] * g["Pmin"], f"MinPower_{name_1}_{t}"

        # Ramp-up and ramp-down constraints for generators
        if t > 0:
            problem += power[name_1, t] - power[name_1, t - 1] <= g["RampUp"], f"RampUp_{name_1}_{t}"
            problem += power[name_1, t - 1] - power[name_1, t] <= g["RampDown"], f"RampDown_{name_1}_{t}"

    for s in storages:
        name_2 = s["name"]
        # Enforce storage minimum and maximum if on
        problem += power[name_2, t] <= status[name_2, t] * s["Pmax"], f"MaxPower_{name_2}_{t}"
        problem += power[name_2, t] >= status[name_2, t] * s["Pmin"], f"MinPower_{name_2}_{t}"

        # Ramp-up and ramp-down constraints for storages
        if t > 0:
            problem += power[name_2, t] - power[name_2, t - 1] <= s["RampUp"], f"RampUp_{name_2}_{t}"
            problem += power[name_2, t - 1] - power[name_2, t] <= s["RampDown"], f"RampDown_{name_2}_{t}"

# Power constraint at t=0 (startup capacity constraints)
    if t == 0:
        for g in generators:
            problem += power[g["name"], t] <= g["Startup"], f"Startup_Constraint_t0_{g['name']}"

# Power constraint at t=0 (startup capacity constraints)
    if t == 0:
        for s in storages:
            problem += power[s["name"], t] <= s["Startup"], f"Startup_Constraint_t0_{s['name']}"

# Solve Problem
problem.solve(GLPK())
# Get the optimal cost
if LpStatus[problem.status] == "Optimal":
    optimal_cost = problem.objective.value()
    print(f"The optimal cost is: {optimal_cost}")
else:
    print(f"The problem could not be solved optimally. Status: {LpStatus[problem.status]}")
# Output Results
for g in generators:
    t = 9  # Set time to 0
    print(f"{g['name']} at time {t}: Power = {power[g['name'], t].varValue}, Status = {status[g['name'], t].varValue}")

for s in storages:
    t = 9  # Set time to 0
    print(f"{s['name']} at time {t}: Power = {power[s['name'], t].varValue}, Status = {status[s['name'], t].varValue}")

for g in generators:
    for t in range(len(demand)):
        print(f"{g['name']} at time {t}: Power = {power[g['name'], t].varValue}, Status = {status[g['name'], t].varValue}")
for s in storages:
    for t in range(len(demand)):
        print(f"{s['name']} at time {t}: Power = {power[s['name'], t].varValue}, Status = {status[s['name'], t].varValue}")

from pulp import LpProblem, LpMinimize, LpVariable, lpSum, LpStatus, GLPK
from pulp import CPLEX_CMD
# Updated Generator Features
generators = [
    {"name": "gen04", "RampUp": 60, "RampDown": 60, "Startup": 150, "Pmax": 300, "Pmin": 150, "StartupCost": 440},
    {"name": "gen05", "RampUp": 100, "RampDown": 100, "Startup": 200, "Pmax": 420, "Pmin": 100, "StartupCost": 210},
    {"name": "gen07", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen10", "RampUp": 100, "RampDown": 100, "Startup": 200, "Pmax": 420, "Pmin": 100, "StartupCost": 200},
    {"name": "gen11", "RampUp": 70, "RampDown": 70, "Startup": 100, "Pmax": 350, "Pmin": 100, "StartupCost": 100},
    {"name": "gen14", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen16", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen19", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 59},
    {"name": "gen20", "RampUp": 50, "RampDown": 50, "Startup": 50, "Pmax": 250, "Pmin": 50, "StartupCost": 100},
    {"name": "gen21", "RampUp": 50, "RampDown": 50, "Startup": 50, "Pmax": 250, "Pmin": 50, "StartupCost": 100},
    {"name": "gen22", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen23", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen24", "RampUp": 40, "RampDown": 40, "Startup": 50, "Pmax": 200, "Pmin": 50, "StartupCost": 100},
    {"name": "gen25", "RampUp": 40, "RampDown": 40, "Startup": 50, "Pmax": 200, "Pmin": 50, "StartupCost": 100},
    {"name": "gen26", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen29", "RampUp": 60, "RampDown": 60, "Startup": 80, "Pmax": 300, "Pmin": 80, "StartupCost": 100},
    {"name": "gen30", "RampUp": 66.7, "RampDown": 66.7, "Startup": 30, "Pmax": 80, "Pmin": 30, "StartupCost": 45},
    {"name": "gen34", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen35", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen36", "RampUp": 60, "RampDown": 60, "Startup": 150, "Pmax": 300, "Pmin": 150, "StartupCost": 440},
    {"name": "gen37", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen39", "RampUp": 60, "RampDown": 60, "Startup": 100, "Pmax": 300, "Pmin": 100, "StartupCost": 440},
    {"name": "gen40", "RampUp": 40, "RampDown": 40, "Startup": 50, "Pmax": 200, "Pmin": 50, "StartupCost": 400},
    {"name": "gen43", "RampUp": 60, "RampDown": 60, "Startup": 100, "Pmax": 300, "Pmin": 100, "StartupCost": 100},
    {"name": "gen44", "RampUp": 60, "RampDown": 60, "Startup": 100, "Pmax": 300, "Pmin": 100, "StartupCost": 100},
    {"name": "gen45", "RampUp": 60, "RampDown": 60, "Startup": 100, "Pmax": 300, "Pmin": 100, "StartupCost": 110},
    {"name": "gen47", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen48", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen51", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen52", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen53", "RampUp": 20, "RampDown": 20, "Startup": 25, "Pmax": 100, "Pmin": 25, "StartupCost": 50},
    {"name": "gen01", "RampUp": 25, "RampDown": 25, "Startup": 5, "Pmax": 30, "Pmin": 5, "StartupCost": 40},
    {"name": "gen02", "RampUp": 25, "RampDown": 25, "Startup": 5, "Pmax": 30, "Pmin": 5, "StartupCost": 40},
    {"name": "gen03", "RampUp": 25, "RampDown": 25, "Startup": 5, "Pmax": 30, "Pmin": 5, "StartupCost": 40},
    {"name": "gen06", "RampUp": 25, "RampDown": 25, "Startup": 10, "Pmax": 30, "Pmin": 10, "StartupCost": 40},
    {"name": "gen08", "RampUp": 25, "RampDown": 25, "Startup": 5, "Pmax": 30, "Pmin": 5, "StartupCost": 40},
    {"name": "gen09", "RampUp": 25, "RampDown": 25, "Startup": 5, "Pmax": 30, "Pmin": 5, "StartupCost": 40},
    {"name": "gen12", "RampUp": 25, "RampDown": 25, "Startup": 8, "Pmax": 30, "Pmin": 8, "StartupCost": 40},
    {"name": "gen13", "RampUp": 25, "RampDown": 25, "Startup": 8, "Pmax": 30, "Pmin": 8, "StartupCost": 40},
    {"name": "gen15", "RampUp": 25, "RampDown": 25, "Startup": 8, "Pmax": 30, "Pmin": 8, "StartupCost": 40},
    {"name": "gen17", "RampUp": 25, "RampDown": 25, "Startup": 8, "Pmax": 30, "Pmin": 8, "StartupCost": 40},
    {"name": "gen18", "RampUp": 25, "RampDown": 25, "Startup": 8, "Pmax": 30, "Pmin": 8, "StartupCost": 40},
    {"name": "gen31", "RampUp": 25, "RampDown": 25, "Startup": 10, "Pmax": 30, "Pmin": 10, "StartupCost": 40},
    {"name": "gen32", "RampUp": 25, "RampDown": 25, "Startup": 5, "Pmax": 30, "Pmin": 5, "StartupCost": 40},
    {"name": "gen33", "RampUp": 16/7, "RampDown": 16/7, "Startup": 5, "Pmax": 20, "Pmin": 5, "StartupCost": 30},
    {"name": "gen38", "RampUp": 25, "RampDown": 25, "Startup": 10, "Pmax": 30, "Pmin": 10, "StartupCost": 40},
    {"name": "gen41", "RampUp": 16/7, "RampDown": 16/7, "Startup": 8, "Pmax": 20, "Pmin": 8, "StartupCost": 30},
    {"name": "gen42", "RampUp": 41/7, "RampDown": 41/7, "Startup": 20, "Pmax": 50, "Pmin": 20, "StartupCost": 45},
    {"name": "gen46", "RampUp": 16/7, "RampDown": 16/7, "Startup": 8, "Pmax": 20, "Pmin": 8, "StartupCost": 30},
    {"name": "gen49", "RampUp": 16/7, "RampDown": 16/7, "Startup": 8, "Pmax": 20, "Pmin": 8, "StartupCost": 30},
    {"name": "gen50", "RampUp": 16/7, "RampDown": 16/7, "Startup": 8, "Pmax": 20, "Pmin": 8, "StartupCost": 30},
    {"name": "gen59", "RampUp": 180, "RampDown": 180, "Startup": 180, "Pmax": 30, "Pmin": 5, "StartupCost": 249/9},
    {"name": "gen60", "RampUp": 120, "RampDown": 120, "Startup": 120, "Pmax": 20, "Pmin": 5, "StartupCost": 248/4},
    {"name": "gen61", "RampUp": 180, "RampDown": 180, "Startup": 180, "Pmax": 30, "Pmin": 5, "StartupCost": 269/1},
    {"name": "gen62", "RampUp": 120, "RampDown": 120, "Startup": 120, "Pmax": 20, "Pmin": 5, "StartupCost": 261/3},
    {"name": "gen63", "RampUp": 180, "RampDown": 180, "Startup": 180, "Pmax": 30, "Pmin": 5, "StartupCost": 297/3},
    {"name": "gen64", "RampUp": 120, "RampDown": 120, "Startup": 120, "Pmax": 20, "Pmin": 5, "StartupCost": 279},

]



storages = [
    {"name": "PSH1", "RampUp": 2, "RampDown": 2, "Startup": 100, "StartupCost": 10, "Pmin": 50, "Pmax": 250},
    {"name": "PSH2", "RampUp": 2, "RampDown": 2, "Startup": 100, "StartupCost": 10, "Pmin": 50, "Pmax": 250},
    {"name": "PSH3", "RampUp": 2, "RampDown": 2, "Startup": 100, "StartupCost": 10, "Pmin": 50, "Pmax": 250},
    {"name": "CAES1", "RampUp": 1, "RampDown": 1, "Startup": 50, "StartupCost": 3, "Pmin": 5, "Pmax": 50},
    {"name": "CAES2", "RampUp": 1, "RampDown": 1, "Startup": 50, "StartupCost": 3, "Pmin": 5, "Pmax": 50},
    {"name": "CAES3", "RampUp": 1, "RampDown": 1, "Startup": 50, "StartupCost": 3, "Pmin": 5, "Pmax": 50},
    {"name": "LiION1", "RampUp": 12, "RampDown": 12, "Startup": 20, "StartupCost": 4, "Pmin": 1, "Pmax": 5},
    {"name": "LiION2", "RampUp": 12, "RampDown": 12, "Startup": 20, "StartupCost": 4, "Pmin": 1, "Pmax": 5},
    {"name": "LiION3", "RampUp": 12, "RampDown": 12, "Startup": 20, "StartupCost": 4, "Pmin": 1, "Pmax": 5},
    {"name": "PSH4", "RampUp": 2, "RampDown": 2, "Startup": 100, "StartupCost": 10, "Pmin": 50, "Pmax": 250},
    {"name": "PSH5", "RampUp": 2, "RampDown": 2, "Startup": 100, "StartupCost": 10, "Pmin": 50, "Pmax": 250},
    {"name": "PSH6", "RampUp": 2, "RampDown": 2, "Startup": 100, "StartupCost": 10, "Pmin": 50, "Pmax": 250},
    {"name": "PSH7", "RampUp": 2, "RampDown": 2, "Startup": 100, "StartupCost": 10, "Pmin": 50, "Pmax": 250},
    {"name": "PSH8", "RampUp": 2, "RampDown": 2, "Startup": 100, "StartupCost": 10, "Pmin": 50, "Pmax": 250},
    {"name": "PSH9", "RampUp": 2, "RampDown": 2, "Startup": 82, "StartupCost": 10, "Pmin": 50, "Pmax": 250},


]
# Demand Upper Bound
demand = [
    3291.96, 2358.38, 1726.88, 3255.33,
    4119.83, 4427.13, 3555.79, 3028.29,
    4099.33, 5044.42, 4487.04, 3549.00
]
#wind of 118-bus IEEE
wind = 3

#Calculate the Net_load
net_load = [demand[i] - wind for i in range(len(demand))]
print(net_load)
# Create Optimization Problem
problem = LpProblem("GeneratorOptimization", LpMinimize)

# Decision Variables
power = {

    **{(g["name"], t): LpVariable(f"power_{g['name']}_{t}", 0, g["Pmax"])
       for g in generators for t in range(len(demand))},
    **{(s["name"], t): LpVariable(f"power_{s['name']}_{t}", 0, s["Pmax"])
       for s in storages for t in range(len(demand))}
}


status = {
    **{(g["name"], t): LpVariable(f"status_{g['name']}_{t}", 0, 1, cat="Binary")
    for g in generators for t in range(len(demand))},
     **{(s["name"], t): LpVariable(f"status_{s['name']}_{t}", 0, 1, cat="Binary")
    for s in storages for t in range(len(demand))}
}

#the estimation of Investment cost of gen26,27,28
Rehab_cost = 200000

# Objective Function: Minimize Cost
problem += lpSum(
   (power[g["name"], t] * 135) - (power.get(("gen05", t), 0) * 35
+ power.get(("gen10", t), 0) * 35) + status[g["name"], 0] * g["StartupCost"] +  Rehab_cost


    # The next line ensures t+1 does not cause an Index Error by excluding the last element of the range
    for g in generators for t in range(len(demand))
) + lpSum(
    power[s["name"], t] * 62 + status[s["name"], 0] * s["StartupCost"]
    for s in storages for t in range(len(demand))
)

# Constraints
for t in range(len(demand)):
    # Meet Demand
    problem += lpSum(power[g["name"], t] for g in generators) + lpSum(power[s["name"], t] for s in storages) >= net_load[t], f"net_load_{t}"

    # Separate loops for generator and storage constraints:
    for g in generators:
        name_1 = g["name"]
        # Enforce generator minimum and maximum if on
        problem += power[name_1, t] <= status[name_1, t] * g["Pmax"], f"MaxPower_{name_1}_{t}"
        problem += power[name_1, t] >= status[name_1, t] * g["Pmin"], f"MinPower_{name_1}_{t}"

        # Ramp-up and ramp-down constraints for generators
        if t > 0:
            problem += power[name_1, t] - power[name_1, t - 1] <= g["RampUp"], f"RampUp_{name_1}_{t}"
            problem += power[name_1, t - 1] - power[name_1, t] <= g["RampDown"], f"RampDown_{name_1}_{t}"

    for s in storages:
        name_2 = s["name"]
        # Enforce storage minimum and maximum if on
        problem += power[name_2, t] <= status[name_2, t] * s["Pmax"], f"MaxPower_{name_2}_{t}"
        problem += power[name_2, t] >= status[name_2, t] * s["Pmin"], f"MinPower_{name_2}_{t}"

        # Ramp-up and ramp-down constraints for storages
        if t > 0:
            problem += power[name_2, t] - power[name_2, t - 1] <= s["RampUp"], f"RampUp_{name_2}_{t}"
            problem += power[name_2, t - 1] - power[name_2, t] <= s["RampDown"], f"RampDown_{name_2}_{t}"

# Power constraint at t=0 (startup capacity constraints)
    if t == 0:
        for g in generators:
            problem += power[g["name"], t] <= g["Startup"], f"Startup_Constraint_t0_{g['name']}"

# Power constraint at t=0 (startup capacity constraints)
    if t == 0:
        for s in storages:
            problem += power[s["name"], t] <= s["Startup"], f"Startup_Constraint_t0_{s['name']}"

# Solve Problem
problem.solve(GLPK())
# Get the optimal cost
if LpStatus[problem.status] == "Optimal":
    optimal_cost = problem.objective.value()
    print(f"The optimal cost is: {optimal_cost}")
else:
    print(f"The problem could not be solved optimally. Status: {LpStatus[problem.status]}")
# Output Results
# Output Results
for g in generators:
    t = 9  # Set time to 0
    print(f"{g['name']} at time {t}: Power = {power[g['name'], t].varValue}, Status = {status[g['name'], t].varValue}")

for s in storages:
    t = 9  # Set time to 0
    print(f"{s['name']} at time {t}: Power = {power[s['name'], t].varValue}, Status = {status[s['name'], t].varValue}")

