# -*- coding: utf-8 -*-
"""Thesis game place.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aBe0e5ea37z1rK5Bvzx7BBGNIRrbPWRp
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
from IPython.display import FileLink
import requests
# Load the CSV file
data = pd.read_csv('output.csv')
print(data)

!pip install pulp

from pulp import LpProblem, LpMinimize, LpVariable, lpSum, LpStatus

# Updated Generator Features
generators = [
    {"name": "gen49", "Pmin": 800, "Pmax": 2000, "RampUp": 22.8571, "RampDown": 22.8571, "Startup": 800, "Shutdown": 30},
    {"name": "gen50", "Pmin": 2500, "Pmax": 5000, "RampUp": 58.5714, "RampDown": 58.5714, "Startup": 2500, "Shutdown": 45},
    {"name": "gen51", "Pmin": 2500, "Pmax": 10000, "RampUp": 200, "RampDown": 200, "Startup": 2500, "Shutdown": 50},
    {"name": "gen52", "Pmin": 2500, "Pmax": 10000, "RampUp": 200, "RampDown": 200, "Startup": 2500, "Shutdown": 50},
    {"name": "gen53", "Pmin": 2500, "Pmax": 10000, "RampUp": 200, "RampDown": 200, "Startup": 2500, "Shutdown": 50},
    {"name": "gen54", "Pmin": 2500, "Pmax": 5000, "RampUp": 58.5714, "RampDown": 58.5714, "Startup": 2500, "Shutdown": 45},
    {"name": "gen55", "Pmin": 500, "Pmax": 3000, "RampUp": 1800, "RampDown": 1800, "Startup": 1800, "Shutdown": 278/4},
    {"name": "gen56", "Pmin": 500, "Pmax": 2000, "RampUp": 1200, "RampDown": 1200, "Startup": 1200, "Shutdown": 281/1},
    {"name": "gen57", "Pmin": 500, "Pmax": 3000, "RampUp": 1800, "RampDown": 1800, "Startup": 1800, "Shutdown": 273},
    {"name": "gen58", "Pmin": 500, "Pmax": 2000, "RampUp": 1200, "RampDown": 1200, "Startup": 1200, "Shutdown": 288/3},
    {"name": "gen59", "Pmin": 500, "Pmax": 3000, "RampUp": 1800, "RampDown": 1800, "Startup": 1800, "Shutdown": 249/9},
    {"name": "gen60", "Pmin": 500, "Pmax": 2000, "RampUp": 1200, "RampDown": 1200, "Startup": 1200, "Shutdown": 248/4},
    {"name": "gen61", "Pmin": 500, "Pmax": 3000, "RampUp": 1800, "RampDown": 1800, "Startup": 1800, "Shutdown": 269/1},
    {"name": "gen62", "Pmin": 500, "Pmax": 2000, "RampUp": 1200, "RampDown": 1200, "Startup": 1200, "Shutdown": 261/3},
    {"name": "gen63", "Pmin": 500, "Pmax": 3000, "RampUp": 1800, "RampDown": 1800, "Startup": 1800, "Shutdown": 297/3},
    {"name": "gen64", "Pmin": 500, "Pmax": 2000, "RampUp": 1200, "RampDown": 1200, "Startup": 1200, "Shutdown": 279}
]


# Demand Upper Bound
demand = [35191.74649535916, 36744.34574306175, 39697.43804097004, 41078.377295862054, 42385.665081611936, 43614.30927773934, 44761.215005569735, 45825.044002571776, 46806.018219009515, 47705.68925737972]

# Create Optimization Problem
problem = LpProblem("GeneratorOptimization", LpMinimize)

# Decision Variables
power = {
    (g["name"], t): LpVariable(f"power_{g['name']}_{t}", 0, g["Pmax"])
    for g in generators for t in range(len(demand))
}
status = {
    (g["name"], t): LpVariable(f"status_{g['name']}_{t}", 0, 1, cat="Binary")
    for g in generators for t in range(len(demand))
}

# Objective Function: Minimize Cost
problem += lpSum(
    power[g["name"], t] * 0.05 + status[g["name"], t] * g["Startup"]
    for g in generators for t in range(len(demand))
)

# Constraints
for t in range(len(demand)):
    # Meet Demand
    problem += lpSum(power[g["name"], t] for g in generators) >= demand[t], f"Demand_{t}"

    for g in generators:
        name = g["name"]
        # Enforce generator minimum and maximum if on
        problem += power[name, t] <= status[name, t] * g["Pmax"], f"MaxPower_{name}_{t}"
        problem += power[name, t] >= status[name, t] * g["Pmin"], f"MinPower_{name}_{t}"

        # Ramp-up and ramp-down constraints
        if t > 0:
            problem += power[name, t] - power[name, t-1] <= g["RampUp"], f"RampUp_{name}_{t}"
            problem += power[name, t-1] - power[name, t] <= g["RampDown"], f"RampDown_{name}_{t}"

# Solve Problem
problem.solve()

# Output Results
print(f"Status: {LpStatus[problem.status]}")
for g in generators:
    for t in range(len(demand)):
        print(f"{g['name']} at time {t}: Power = {power[g['name'], t].varValue}, Status = {status[g['name'], t].varValue}")

from pulp import LpProblem, LpMinimize, LpVariable, lpSum, LpStatus

# Updated Generator Features
generators = [
    {"name": "gen49", "RampUp": 22.8571, "RampDown": 22.8571, "Startup": 800, "StartupCost": 30, "Pmax": 2000, "Pmin": 800},
    {"name": "gen50", "RampUp": 58.5714, "RampDown": 58.5714, "Startup": 2500, "StartupCost": 45, "Pmax": 5000, "Pmin": 2500},
    {"name": "gen51", "RampUp": 200, "RampDown": 200, "Startup": 2500, "StartupCost": 50, "Pmax": 10000, "Pmin": 2500},
    {"name": "gen52", "RampUp": 200, "RampDown": 200, "Startup": 2500, "StartupCost": 50, "Pmax": 10000, "Pmin": 2500},
    {"name": "gen53", "RampUp": 200, "RampDown": 200, "Startup": 2500, "StartupCost": 50, "Pmax": 10000, "Pmin": 2500},
    {"name": "gen54", "RampUp": 58.5714, "RampDown": 58.5714, "Startup": 2500, "StartupCost": 45, "Pmax": 5000, "Pmin": 2500},
    {"name": "gen55", "RampUp": 1800, "RampDown": 1800, "Startup": 1800, "StartupCost": 69.5, "Pmax": 3000, "Pmin": 500},
    {"name": "gen56", "RampUp": 1200, "RampDown": 1200, "Startup": 1200, "StartupCost": 281, "Pmax": 2000, "Pmin": 500},
    {"name": "gen57", "RampUp": 1800, "RampDown": 1800, "Startup": 1800, "StartupCost": 273, "Pmax": 3000, "Pmin": 500},
    {"name": "gen58", "RampUp": 1200, "RampDown": 1200, "Startup": 1200, "StartupCost": 96, "Pmax": 2000, "Pmin": 500},
    {"name": "gen59", "RampUp": 1800, "RampDown": 1800, "Startup": 1800, "StartupCost": 27.67, "Pmax": 3000, "Pmin": 500},
    {"name": "gen60", "RampUp": 1200, "RampDown": 1200, "Startup": 1200, "StartupCost": 62, "Pmax": 2000, "Pmin": 500},
    {"name": "gen61", "RampUp": 1800, "RampDown": 1800, "Startup": 1800, "StartupCost": 269, "Pmax": 3000, "Pmin": 500},
    {"name": "gen62", "RampUp": 1200, "RampDown": 1200, "Startup": 1200, "StartupCost": 87, "Pmax": 2000, "Pmin": 500},
    {"name": "gen63", "RampUp": 1800, "RampDown": 1800, "Startup": 1800, "StartupCost": 99, "Pmax": 3000, "Pmin": 500},
    {"name": "gen64", "RampUp": 1200, "RampDown": 1200, "Startup": 1200, "StartupCost": 279, "Pmax": 2000, "Pmin": 500},
]

# Demand Upper Bound
demand = [35191.74649535916, 36744.34574306175, 39697.43804097004, 41078.377295862054, 42385.665081611936,
          43614.30927773934, 44761.215005569735, 45825.044002571776, 46806.018219009515, 47705.68925737972]

# Create Optimization Problem
problem = LpProblem("GeneratorOptimization", LpMinimize)

# Decision Variables
power = {
    (g["name"], t): LpVariable(f"power_{g['name']}_{t}", 0, g["Pmax"])
    for g in generators for t in range(len(demand))
}
status = {
    (g["name"], t): LpVariable(f"status_{g['name']}_{t}", 0, 1, cat="Binary")
    for g in generators for t in range(len(demand))
}

# Objective Function: Minimize Cost
problem += lpSum(
    power[g["name"], t] * 0.05 + status[g["name"], t] * g["Startup"]
    for g in generators for t in range(len(demand))
)

# Constraints
for t in range(len(demand)):
    # Meet Demand
    problem += lpSum(power[g["name"], t] for g in generators) >= demand[t], f"Demand_{t}"

    for g in generators:
        name = g["name"]
        # Enforce generator minimum and maximum if on
        problem += power[name, t] <= status[name, t] * g["Pmax"], f"MaxPower_{name}_{t}"
        problem += power[name, t] >= status[name, t] * g["Pmin"], f"MinPower_{name}_{t}"

        # Ramp-up and ramp-down constraints
        if t > 0:
            problem += power[name, t] - power[name, t-1] <= g["RampUp"], f"RampUp_{name}_{t}"
            problem += power[name, t-1] - power[name, t] <= g["RampDown"], f"RampDown_{name}_{t}"

# Solve Problem
problem.solve()

# Output Results
print(f"Status: {LpStatus[problem.status]}")
for g in generators:
    for t in range(len(demand)):
        print(f"{g['name']} at time {t}: Power = {power[g['name'], t].varValue}, Status = {status[g['name'], t].varValue}")



import matplotlib.pyplot as plt

# Extract results for plotting
time_steps = range(len(demand))
power_results = {g["name"]: [power[g["name"], t].varValue for t in time_steps] for g in generators}
demand_results = demand

# Plot the results
plt.figure(figsize=(12, 6))

# Plot power generation for each generator
for gen_name, gen_power in power_results.items():
    plt.plot(time_steps, gen_power, label=f"{gen_name} Power")

# Plot the demand curve
plt.plot(time_steps, demand_results, label="Demand", color="black", linestyle="--", linewidth=2)

# Customize the plot
plt.title("Generator Power Output and Demand Over Time")
plt.xlabel("Time Steps")
plt.ylabel("Power (MW)")
plt.legend()
plt.grid(True)

# Show the plot
plt.show()

